%% input %%
% get the parent directory

uiwait(msgbox('Load parent folder'));
d = uigetdir('');
matlab_folder = cd;

cd(d)

listing = dir('**/*turnover_average.mat');

cd(matlab_folder) 

%% load files and save data %%
n_files = length(listing);
data = [];

for k = 1:n_files
    
    file = listing(k).name;
    directory = listing(k).folder;
    
    data_temp = load (fullfile ([directory, '/', file]));
    
    data{k,1} = data_temp;
end

%% turnover boxplot %%

g = [repmat(1,length(data{3,1}.data),1);...
    repmat(2,length(data{2,1}.data),1);...
    repmat(3,length(data{7,1}.data),1);...
    repmat(4,length(data{8,1}.data),1);...
    repmat(5,length(data{1,1}.MLCK_turnover_average),1);...
    repmat(6,length(data{4,1}.ena_ctrl_turnover_average),1);...
    repmat(7,length(data{5,1}.ena_mut_turnover_average),1);...
    repmat(8,length(data{6,1}.ena_over_turnover_average),1);...
    repmat(9,length(data{9,1}.data),1);...
    repmat(10,length(data{10,1}.ssh_mut_turnover_average),1);...
    repmat(11,length(data{11,1}.ssh_over_turnover_average),1)];

turnover = [data{3,1}.data;...
    data{2,1}.data;...
    data{7,1}.data;...
    data{8,1}.data;...
    data{1,1}.MLCK_turnover_average;...
    data{4,1}.ena_ctrl_turnover_average;...
    data{5,1}.ena_mut_turnover_average;...
    data{6,1}.ena_over_turnover_average;...
    data{9,1}.data;...
    data{10,1}.ssh_mut_turnover_average;...
    data{11,1}.ssh_over_turnover_average];

figure
boxplot(turnover, g)
set(gca,'xtick',1:11,...
    'xticklabel',{'ctrl' ...
    'cofilin' ...
    'myosin' ...
    'myosin-cofilin' ...
    'MLCK constitutively active' ...
    'ena control' 'ena mutant' 'ena overexpressed' ...
    'sn28' ...
    'ssh mutant' 'ssh overexpressed'},...
    'xticklabelrotation',45)
ylabel('Actin turnover [A.U.]')
set(findall(gcf, '-property', 'FontSize'), 'FontSize', 14)
set(gcf, 'InvertHardCopy', 'off');
set(gcf, 'Color', [1 1 1]); 

