%% input %%
% get the parent directory

uiwait(msgbox('Load parent folder'));
d = uigetdir('');
matlab_folder = cd;

cd(d)

listing = dir('**/*divergence_average.mat');

cd(matlab_folder) 

%% load files and save data %%
n_files = length(listing);
data = [];

for k = 1:n_files
    
    file = listing(k).name;
    directory = listing(k).folder;
    
    data_temp = load (fullfile ([directory, '/', file]));
    
    data{k,1} = data_temp;
end

%% divergence boxplot %%

% {'MLCK_divergence_average.mat';       1 > 5
% 'cofilin_divergence_average.mat';     2 > 2
% 'ctrl_divergence_average.mat';        3 > 1
% 'ena_ctrl_divergence_average.mat';    4 > 6
% 'ena_mut_divergence_average.mat';     5 > 7
% 'ena_over_divergence_average.mat';    6 > 8
% 'myosin_divergence_average.mat';      7 > 3
% 'myocof_divergence_average.mat';      8 > 4
% 'sn28_divergence_average.mat';        9 > 9
% 'ssh_mut_divergence_average.mat';     10 > 10
% 'ssh_over_divergence_average.mat'}    11 > 11

g = [repmat(1,length(data{3,1}.data),1);...
    repmat(2,length(data{2,1}.data),1);...
    repmat(3,length(data{7,1}.data),1);...
    repmat(4,length(data{8,1}.data),1);...
    repmat(5,length(data{1,1}.MLCK_divergence_average),1);...
    repmat(6,length(data{4,1}.ena_ctrl_divergence_average),1);...
    repmat(7,length(data{5,1}.ena_mut_divergence_average),1);...
    repmat(8,length(data{6,1}.ena_over_divergence_average),1);...
    repmat(9,length(data{9,1}.data),1);...
    repmat(10,length(data{10,1}.ssh_mut_divergence_average),1);...
    repmat(11,length(data{11,1}.ssh_over_divergence_average),1)];

divergence = [data{3,1}.data;...
    data{2,1}.data;...
    data{7,1}.data;...
    data{8,1}.data;...
    data{1,1}.MLCK_divergence_average;...
    data{4,1}.ena_ctrl_divergence_average;...
    data{5,1}.ena_mut_divergence_average;...
    data{6,1}.ena_over_divergence_average;...
    data{9,1}.data;...
    data{10,1}.ssh_mut_divergence_average;...
    data{11,1}.ssh_over_divergence_average];

figure
boxplot(divergence, g)
set(gca,'xtick',1:11,...
    'xticklabel',{'ctrl' ...
    'cofilin' ...
    'myosin' ...
    'myosin-cofilin' ...
    'MLCK constitutively active' ...
    'ena control' 'ena mutant' 'ena overexpressed' ...
    'sn28' ...
    'ssh mutant' 'ssh overexpressed'},...
    'xticklabelrotation',45)
ylabel('Divergence [A.U.]')
set(findall(gcf, '-property', 'FontSize'), 'FontSize', 14)
set(gcf, 'InvertHardCopy', 'off');
set(gcf, 'Color', [1 1 1]); 

