g = [repmat(2,length(MLCK_divergence_average),1);...
    repmat(3,length(ssh_mut_divergence_average),1);...
    repmat(4,length(ssh_over_divergence_average),1);...
    repmat(5,length(ena_ctrl_divergence_average),1);...
    repmat(6,length(ena_mut_divergence_average),1);...
    repmat(7,length(ena_over_divergence_average),1)];

flow_speed = [MLCK_flow_speed_average;...
    ssh_mut_flow_speed_average;...
    ssh_over_flow_speed_average;...
    ena_ctrl_flow_speed_average;...
    ena_mut_flow_speed_average;...
    ena_over_flow_speed_average];

divergence = [MLCK_divergence_average;...
    ssh_mut_divergence_average;...
    ssh_over_divergence_average;...
    ena_ctrl_divergence_average;...
    ena_mut_divergence_average;...
    ena_over_divergence_average];

turnover = [MLCK_turnover_average;...
    ssh_mut_turnover_average;...
    ssh_over_turnover_average;...
    ena_ctrl_turnover_average;...
    ena_mut_turnover_average;...
    ena_over_turnover_average];

streamlines_percentage = [MLCK_streamlines_percentage_average;...
    ssh_mut_streamlines_percentage_average;...
    ssh_over_streamlines_percentage_average;...
    ena_ctrl_streamlines_percentage_average;...
    ena_mut_streamlines_percentage_average;...
    ena_over_streamlines_percentage_average];

%% PLOT %%

figure
boxplot(flow_speed, g)
set(findall(gcf, '-property', 'FontSize'), 'FontSize', 14)
set(gca,'xtick',1:6,...
    'xticklabel',{'MLCK constitutively active' 'ssh mutant' 'ssh overexpressed' 'ena control' 'ena mutant' 'ena overexpressed'},...
    'xticklabelrotation',45)
ylabel('Flow speed [um/min]')


figure
boxplot(divergence, g)
set(findall(gcf, '-property', 'FontSize'), 'FontSize', 14)
set(gca,'xtick',1:6,...
    'xticklabel',{'MLCK constitutively active' 'ssh mutant' 'ssh overexpressed' 'ena control' 'ena mutant' 'ena overexpressed'},...
    'xticklabelrotation',45)
ylabel('Divergence [A.U.]')

figure
boxplot(turnover, g)
set(findall(gcf, '-property', 'FontSize'), 'FontSize', 14)
set(gca,'xtick',1:6,...
    'xticklabel',{'MLCK constitutively active' 'ssh mutant' 'ssh overexpressed' 'ena control' 'ena mutant' 'ena overexpressed'},...
    'xticklabelrotation',45)
ylabel('Turnover [A.U.]')

figure
boxplot(streamlines_percentage, g)
set(findall(gcf, '-property', 'FontSize'), 'FontSize', 14)
set(gca,'xtick',1:6,...
    'xticklabel',{'MLCK constitutively active' 'ssh mutant' 'ssh overexpressed' 'ena control' 'ena mutant' 'ena overexpressed'},...
    'xticklabelrotation',45)
ylabel('Streamlines at primary sink [%]')
ylim([0 100])
